package com.example.todonotioncompose.data.Keyword

import androidx.annotation.NonNull
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity
data class Keyword(
    // TODO: declare the id to be an autogenerated primary key
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    //search keyWord
    @NonNull @ColumnInfo(name = "key_name")
    val keyName: String,

    )